In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

In [3]:
data=pd.read_csv('wine_quality_classification.csv')
data.head(2)

fixed_acidity  residual_sugar  alcohol  density quality_label
0            9.3             6.4     13.6   1.0005          high
1           11.2             2.0     14.0   0.9912        medium

In [5]:
data.columns

Index(['fixed_acidity', 'residual_sugar', 'alcohol', 'density',
       'quality_label'],
      dtype='object')

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   fixed_acidity   1000 non-null   float64
 1   residual_sugar  1000 non-null   float64
 2   alcohol         1000 non-null   float64
 3   density         1000 non-null   float64
 4   quality_label   1000 non-null   object 
dtypes: float64(4), object(1)
memory usage: 39.2+ KB


In [8]:
data.shape

(1000, 5)

In [9]:
data.describe()

fixed_acidity  residual_sugar      alcohol      density
count    1000.000000      1000.00000  1000.000000  1000.000000
mean       10.174300         7.69200    11.039900     0.997505
std         3.452693         4.20892     1.760283     0.004300
min         4.000000         0.50000     8.000000     0.990000
25%         7.100000         4.10000     9.500000     0.993900
50%        10.400000         7.55000    11.000000     0.997400
75%        13.125000        11.50000    12.600000     1.001200
max        16.000000        15.00000    14.000000     1.005000

In [10]:
data.sample()

fixed_acidity  residual_sugar  alcohol  density quality_label
22            8.7             3.0     10.4   1.0047           low

In [11]:
X=data.drop(['quality_label'],axis=1)
y=data['quality_label']

In [12]:
scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)

In [47]:
X_test,X_train,y_test,y_train=train_test_split(X_scaled,y,test_size=0.3,random_state=42)

In [48]:
model=SVC(kernel='linear')
model.fit(X_train,y_train)

SVC(kernel='linear')

In [49]:
y_pred=model.predict(X_test)

In [50]:
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy=accuracy_score(y_test,y_pred)
print(accuracy)
c=classification_report(y_test,y_pred)
print(c)

[[175   0  58]
 [160   0  52]
 [190   0  65]]
0.34285714285714286
              precision    recall  f1-score   support

        high       0.33      0.75      0.46       233
         low       0.00      0.00      0.00       212
      medium       0.37      0.25      0.30       255

    accuracy                           0.34       700
   macro avg       0.23      0.34      0.25       700
weighted avg       0.25      0.34      0.26       700



c:\Users\Acer\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Acer\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Acer\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(averag

In [35]:
#rbf

rbf_model=SVC(kernel='rbf')
rbf_model.fit(X_train,y_train)

SVC()

In [36]:
y_pred2=rbf_model.predict(X_test)

In [37]:
cm=confusion_matrix(y_test,y_pred2)
print(cm)
accuracy=accuracy_score(y_test,y_pred2)
print(accuracy)
c=classification_report(y_test,y_pred2)
print(c)

[[156  94  57]
 [106 103  58]
 [150  98  78]]
0.37444444444444447
              precision    recall  f1-score   support

        high       0.38      0.51      0.43       307
         low       0.35      0.39      0.37       267
      medium       0.40      0.24      0.30       326

    accuracy                           0.37       900
   macro avg       0.38      0.38      0.37       900
weighted avg       0.38      0.37      0.37       900



In [40]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [42]:
model3=DecisionTreeClassifier()
model3.fit(X_train,y_train)

y_pred3=model3.predict(X_test)

In [43]:
cm=confusion_matrix(y_test,y_pred3)
print(cm)
accuracy=accuracy_score(y_test,y_pred3)
print(accuracy)
c=classification_report(y_test,y_pred3)
print(c)

[[121 121  65]
 [109 107  51]
 [116 129  81]]
0.3433333333333333
              precision    recall  f1-score   support

        high       0.35      0.39      0.37       307
         low       0.30      0.40      0.34       267
      medium       0.41      0.25      0.31       326

    accuracy                           0.34       900
   macro avg       0.35      0.35      0.34       900
weighted avg       0.36      0.34      0.34       900



In [44]:
model4=RandomForestClassifier()
model4.fit(X_train,y_train)

y_pred4=model4.predict(X_test)

In [45]:
cm=confusion_matrix(y_test,y_pred4)
print(cm)
accuracy=accuracy_score(y_test,y_pred4)
print(accuracy)
c=classification_report(y_test,y_pred4)
print(c)

[[140  84  83]
 [108  82  77]
 [125  97 104]]
0.3622222222222222
              precision    recall  f1-score   support

        high       0.38      0.46      0.41       307
         low       0.31      0.31      0.31       267
      medium       0.39      0.32      0.35       326

    accuracy                           0.36       900
   macro avg       0.36      0.36      0.36       900
weighted avg       0.36      0.36      0.36       900



In [51]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(model, X, y, cv=5)
print(f"Cross-Validation Scores: {scores}")
print(f"Mean Accuracy: {scores.mean() * 100:.2f}%")
 

Cross-Validation Scores: [0.405 0.38  0.415 0.355 0.355]
Mean Accuracy: 38.20%


In [54]:
from sklearn.linear_model import LogisticRegression

model4=LogisticRegression()
model4.fit(X_train,y_train)

y_pred4=model4.predict(X_test)

In [55]:
cm=confusion_matrix(y_test,y_pred4)
print(cm)
accuracy=accuracy_score(y_test,y_pred4)
print(accuracy)
c=classification_report(y_test,y_pred4)
print(c)

[[133  35  65]
 [113  36  63]
 [130  51  74]]
0.34714285714285714
              precision    recall  f1-score   support

        high       0.35      0.57      0.44       233
         low       0.30      0.17      0.22       212
      medium       0.37      0.29      0.32       255

    accuracy                           0.35       700
   macro avg       0.34      0.34      0.33       700
weighted avg       0.34      0.35      0.33       700

